game: Map.hpp Menu.hpp Player.hpp Space.hpp Coffee_Shop.hpp Center.hpp Star_Wars.hpp Harry_Potter.hpp Dr_Seuss.hpp Blank.hpp
	g++ main.cpp Map.cpp Menu.cpp Player.cpp Space.cpp Coffee_Shop.cpp Center.cpp Star_Wars.cpp Harry_Potter.cpp Dr_Seuss.cpp Blank.cpp -o play
clean:
	rm -f *o play